baseURL = 'https://nel.re/'
languageCode = 'en-us'
title = 'Nel.re'
theme = [ "nel-theme", "hugo-easy-gallery" ]

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menus.main]]
    identifier = "Archive"
    name = 'Archive'
    pageRef = '/archive'
    weight = 20

  [[menus.main]]
    identifier = "Notes"
    name = 'Notes'
    pageRef = '/notes'
    weight = 30

