baseURL = 'https://nel.re/'
languageCode = 'en-us'
title = 'Nel.re'
theme = [ "nel-theme", "hugo-easy-gallery" ]

[menu]

  [[menus.main]]
    identifier = "test"
    name = 'test'
    pageRef = '/test'
    weight = 20

  [[menus.main]]
    identifier = "Archives"
    name = 'Archives'
    pageRef = '/archives'
    weight = 20

  [[menus.main]]
    identifier = "Notes"
    name = 'Notes'
    pageRef = '/notes'
    weight = 30

