baseURL = 'https://nel.re/'
languageCode = 'en-us'
title = 'Nel.re'
theme = ["hugo-video", "nel-theme", "hugo-easy-gallery" ]

[menu]

  [[menus.main]]
    identifier = "Art"
    name = 'Art'
    pageRef = '/art'
    weight = 20

  [[menus.main]]
    identifier = "Blog"
    name = 'Blog'
    pageRef = '/blog'
    weight = 30

