name = 'Nel'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'nel.re theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/angelocarly/nel.re'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

[author]
  name = 'Angelo Carly'
  homepage = 'https://nel.re'
